name: "Release"
on:
  release:
    types: [released]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Clean
        run: dotnet clean

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: "/home/runner/work/EliteAPI/EliteAPI/EliteAPI/bin/Release"
          if-no-files-found: error

  add-to-release:
    needs: [build]
    name: Add assets to release
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Zip release assets
        uses: TheDoctor0/zip-release@0.4.1
        with:
          filename: release.zip
          path: "./netstandard2.0/publish"

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: "release.zip"
          asset_name: "EliteAPI"
          asset_content_type: application/zip

  publish-nuget:
    needs: [build]
    name: Publish to NuGet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
          
      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.5
        if: ${{ env.GitVersion_PreReleaseLabel != 'alpha' && env.GitVersion_PreReleaseLabel != 'beta'}}
        with:
          PROJECT_FILE_PATH: EliteAPI/EliteAPI.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_KEY}}
      
      - name: Unlist alpha and beta packages
        if: ${{ env.GitVersion_PreReleaseLabel != 'alpha' && env.GitVersion_PreReleaseLabel != 'beta'}}
        uses: darenm/unlist-nuget@v1
        with:
          NUGET_PACKAGE: EliteAPI
          VERSION_REGEX: (.*alpha.*)|(.*beta.*)
          NUGET_KEY: ${{secrets.NUGET_KEY}}

