name: Update version
on: push

jobs:
  setup-dotnet:
    name: Setup .NET
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["5.0.x"]

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{matrix.dotnet-version}}

  update-version:
    name: Update version
    needs: [setup-dotnet]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gitversion-version: ["5.6.0"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup GitVersion
        run: dotnet tool install --global GitVersion.Tool --version ${{matrix.gitversion-version}}

      - name: Fetch tags for GitVersion
        run: git fetch --tags

      - name: Fetch master for GitVersion
        if: github.ref != 'refs/heads/master'
        run: git branch --create-reflog master origin/master

      - name: Update version
        id: VERSION
        run: dotnet-gitversion /updateprojectfiles /updateassemblyinfo /output buildserver
        
      - run: echo ${{steps.VERSION.outputs}}

      - name: Apply changes
        uses: EndBug/add-and-commit@v6.2.0
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "Updated project version"
